CURATED_PROBLEMS = [
    {
        "title": "Running Totals",
        "topic": "basics",
        "difficulty": 1,
        "description": "Given a list of integers, return a list where each position contains the sum of all values up to that position. Implement solution(nums) and return the new list.",
        "starter_code": "def solution(nums):\n    # Return the running total at each position\n    pass",
        "constraints": "0 <= len(nums) <= 100,000; -10,000 <= nums[i] <= 10,000",
        "sample_input": "nums = [4, -1, 3]",
        "sample_output": "[4, 3, 6]",
        "solution": "def solution(nums):\n    totals = []\n    current = 0\n    for value in nums:\n        current += value\n        totals.append(current)\n    return totals",
        "hints": ["Keep a running sum as you scan the list.", "Append the updated sum after processing each value."],
        "test_cases": [
            {"input": "([4, -1, 3],)", "expected": "[4, 3, 6]"},
            {"input": "([-2, 5],)", "expected": "[-2, 3]"},
            {"input": "([],)", "expected": "[]"},
        ],
    },
    {
        "title": "Stable Zero Compaction",
        "topic": "arrays",
        "difficulty": 1,
        "description": "Given a list of integers, return a new list with every zero moved to the end. Keep the non-zero values in their original order.",
        "starter_code": "def solution(nums):\n    # Keep non-zero values in order, then append the zeros\n    pass",
        "constraints": "1 <= len(nums) <= 100,000; -2^31 <= nums[i] <= 2^31 - 1",
        "sample_input": "nums = [0, 1, 0, 3, 12]",
        "sample_output": "[1, 3, 12, 0, 0]",
        "solution": "def solution(nums):\n    nonzero = [value for value in nums if value != 0]\n    return nonzero + [0] * (len(nums) - len(nonzero))",
        "hints": ["Collect non-zero values in one pass.", "The number of zeros is the input length minus the non-zero count."],
        "test_cases": [
            {"input": "([0, 1, 0, 3, 12],)", "expected": "[1, 3, 12, 0, 0]"},
            {"input": "([0],)", "expected": "[0]"},
            {"input": "([2, 1, 3],)", "expected": "[2, 1, 3]"},
        ],
    },
    {
        "title": "First Unique Character",
        "topic": "strings",
        "difficulty": 1,
        "description": "Given a string, return the index of its first character that appears exactly once. Return -1 when every character repeats.",
        "starter_code": "def solution(text):\n    # Return the index of the first character that occurs once\n    pass",
        "constraints": "0 <= len(text) <= 100,000; text contains lowercase English letters",
        "sample_input": "text = \"swiss\"",
        "sample_output": "1",
        "solution": "def solution(text):\n    counts = {}\n    for char in text:\n        counts[char] = counts.get(char, 0) + 1\n    for index, char in enumerate(text):\n        if counts[char] == 1:\n            return index\n    return -1",
        "hints": ["Count how often each character appears.", "Scan the original string again so the first unique character stays first."],
        "test_cases": [
            {"input": "('swiss',)", "expected": "1"},
            {"input": "('aabb',)", "expected": "-1"},
            {"input": "('leetcode',)", "expected": "0"},
        ],
    },
    {
        "title": "Nested List Sum",
        "topic": "recursion",
        "difficulty": 1,
        "description": "A list may contain integers or other lists. Return the sum of every integer at every nesting depth. Implement solution(values) recursively.",
        "starter_code": "def solution(values):\n    # Recursively sum integers in this list and its nested lists\n    pass",
        "constraints": "0 <= total number of values <= 10,000; nesting depth <= 100; values are integers or lists",
        "sample_input": "values = [1, [2, [3]], 4]",
        "sample_output": "10",
        "solution": "def solution(values):\n    total = 0\n    for value in values:\n        total += solution(value) if isinstance(value, list) else value\n    return total",
        "hints": ["The sum of a list is the sum of each item.", "When an item is itself a list, solve that smaller list recursively."],
        "test_cases": [
            {"input": "([1, [2, [3]], 4],)", "expected": "10"},
            {"input": "([],)", "expected": "0"},
            {"input": "([[-2], [5]],)", "expected": "3"},
        ],
    },
    {
        "title": "Order by Distance",
        "topic": "sorting",
        "difficulty": 2,
        "description": "Given a list of integers and a pivot, return the values sorted by distance from the pivot. When two values have equal distance, put the smaller value first.",
        "starter_code": "def solution(nums, pivot):\n    # Sort by (distance from pivot, value)\n    pass",
        "constraints": "0 <= len(nums) <= 100,000; -10^9 <= nums[i], pivot <= 10^9",
        "sample_input": "nums = [8, 1, 5, 3], pivot = 4",
        "sample_output": "[3, 5, 1, 8]",
        "solution": "def solution(nums, pivot):\n    return sorted(nums, key=lambda value: (abs(value - pivot), value))",
        "hints": ["A sort key can contain more than one value.", "Use distance as the primary key and the value as the tie-breaker."],
        "test_cases": [
            {"input": "([8, 1, 5, 3], 4)", "expected": "[3, 5, 1, 8]"},
            {"input": "([2, 9, 4], 6)", "expected": "[4, 9, 2]"},
            {"input": "([7, 3, 5, 1], 4)", "expected": "[3, 5, 1, 7]"},
        ],
    },
    {
        "title": "First Position in a Sorted List",
        "topic": "searching",
        "difficulty": 1,
        "description": "Given a sorted list that may contain duplicates and a target value, return the target's first index. Return -1 if it is absent. Aim for O(log n) time.",
        "starter_code": "def solution(nums, target):\n    # Use binary search and keep looking left after a match\n    pass",
        "constraints": "0 <= len(nums) <= 100,000; nums is sorted in non-decreasing order",
        "sample_input": "nums = [1, 2, 2, 2, 4], target = 2",
        "sample_output": "1",
        "solution": "def solution(nums, target):\n    left, right = 0, len(nums)\n    while left < right:\n        middle = (left + right) // 2\n        if nums[middle] < target:\n            left = middle + 1\n        else:\n            right = middle\n    return left if left < len(nums) and nums[left] == target else -1",
        "hints": ["Use a half-open search range [left, right).", "When the middle value is at least the target, keep the left half."],
        "test_cases": [
            {"input": "([1, 2, 2, 2, 4], 2)", "expected": "1"},
            {"input": "([1, 3, 5], 2)", "expected": "-1"},
            {"input": "([], 7)", "expected": "-1"},
        ],
    },
    {
        "title": "Minimum Coin Count",
        "topic": "dynamic_programming",
        "difficulty": 2,
        "description": "Given coin denominations and a target amount, return the fewest coins needed to make that amount. You may use each denomination any number of times. Return -1 if the amount cannot be made.",
        "starter_code": "def solution(coins, amount):\n    # Build the best answer for each amount from 0 up to amount\n    pass",
        "constraints": "1 <= len(coins) <= 20; 1 <= coins[i] <= 10,000; 0 <= amount <= 10,000",
        "sample_input": "coins = [1, 2, 5], amount = 11",
        "sample_output": "3",
        "solution": "def solution(coins, amount):\n    best = [amount + 1] * (amount + 1)\n    best[0] = 0\n    for current in range(1, amount + 1):\n        for coin in coins:\n            if coin <= current:\n                best[current] = min(best[current], best[current - coin] + 1)\n    return best[amount] if best[amount] <= amount else -1",
        "hints": ["Let best[x] store the fewest coins needed for amount x.", "For each amount, try adding each coin that does not exceed it."],
        "test_cases": [
            {"input": "([1, 2, 5], 11)", "expected": "3"},
            {"input": "([2], 3)", "expected": "-1"},
            {"input": "([3, 4], 0)", "expected": "0"},
        ],
    },
    {
        "title": "Reachable Network Nodes",
        "topic": "graphs",
        "difficulty": 2,
        "description": "An undirected graph has n nodes numbered from 0 to n - 1. Given its edges and a start node, return how many nodes can be reached from start.",
        "starter_code": "def solution(n, edges, start):\n    # Build an adjacency list, then traverse from start\n    pass",
        "constraints": "1 <= n <= 100,000; 0 <= len(edges) <= 200,000; each edge joins two different valid nodes",
        "sample_input": "n = 5, edges = [[0, 1], [1, 2], [3, 4]], start = 0",
        "sample_output": "3",
        "solution": "def solution(n, edges, start):\n    graph = [[] for _ in range(n)]\n    for first, second in edges:\n        graph[first].append(second)\n        graph[second].append(first)\n    seen = {start}\n    stack = [start]\n    while stack:\n        node = stack.pop()\n        for neighbor in graph[node]:\n            if neighbor not in seen:\n                seen.add(neighbor)\n                stack.append(neighbor)\n    return len(seen)",
        "hints": ["Represent each node's neighbors with an adjacency list.", "A depth-first or breadth-first traversal visits exactly the reachable nodes."],
        "test_cases": [
            {"input": "(5, [[0, 1], [1, 2], [3, 4]], 0)", "expected": "3"},
            {"input": "(4, [[0, 1], [0, 2], [0, 3]], 0)", "expected": "4"},
            {"input": "(3, [], 1)", "expected": "1"},
        ],
    },
    {
        "title": "Binary Tree Height",
        "topic": "trees",
        "difficulty": 2,
        "description": "A binary tree is given in level-order form, where null marks an empty child. Return the number of nodes on its longest root-to-leaf path. An empty tree has height 0.",
        "starter_code": "def solution(level_order):\n    # Traverse the level-order representation and track depth\n    pass",
        "constraints": "0 <= len(level_order) <= 10,000; values are integers or null",
        "sample_input": "level_order = [3, 9, 20, null, null, 15, 7]",
        "sample_output": "3",
        "solution": "from collections import deque\n\ndef solution(level_order):\n    if not level_order or level_order[0] is None:\n        return 0\n    queue = deque([level_order[0]])\n    index = 1\n    height = 0\n    while queue:\n        for _ in range(len(queue)):\n            queue.popleft()\n            for _ in range(2):\n                if index < len(level_order):\n                    child = level_order[index]\n                    index += 1\n                    if child is not None:\n                        queue.append(child)\n        height += 1\n    return height",
        "hints": ["Process the tree one level at a time.", "Only non-null children belong in the next level's queue."],
        "test_cases": [
            {"input": "([3, 9, 20, None, None, 15, 7],)", "expected": "3"},
            {"input": "([1, 2, None, 3],)", "expected": "3"},
            {"input": "([],)", "expected": "0"},
        ],
    },
]